Repository rsksmart/lumino-light-client-sdk, pull requests merged in 2020-10, with the labels that each got.

#92 RLP-806 Allow the SDK to work without notifiers
  src/Lumino/index.js
  src/store/actions/close.js
  src/store/reducers/channelReducer.js
  test/store/actions/close.test.js
Labels: enhancement, rif notifier

#97 RLP-831 Trigger settlement callback
  src/store/actions/settle.js
Labels: settlement light

#96 RLP-819 Message Identifier on settlement request
  src/store/actions/settle.js
  src/store/epics/index.js
  src/utils/messageManager.js
  src/utils/pack.js
Labels: settlement light

#93 RLP-792 Light Client Unlock & Register Secret
  __mocks__/rns.js
  src/config/channelStates.js
  src/config/messagesConstants.js
  src/scripts/constants.js
  src/scripts/secret.js
  src/scripts/unlock.js
  src/store/actions/notifier.js
  src/store/actions/payment.js
  src/store/actions/secret.js
  src/store/actions/tokens.js
  src/store/actions/types.js
  src/store/actions/unlock.js
  src/store/functions/rns.js
  src/store/functions/tokens.js
  src/store/reducers/channelReducer.js
  src/store/reducers/paymentIdsReducer.js
  src/store/reducers/paymentsReducer.js
  src/utils/callbacks.js
  src/utils/messageManager.js
  src/utils/pack.js
  src/utils/web3.js
  test/store/actions/polling.test.js
  test/store/actions/tokens.test.js
  test/store/functions/rns.test.js
  test/store/functions/tokens.test.js
  test/store/reducers/channel.test.js
  test/store/reducers/channelStates.test.js
  test/store/reducers/client.test.js
  test/store/reducers/notifier.test.js
  test/store/reducers/payment.test.js
  test/store/reducers/paymentIds.test.js
  test/store/reducers/tokenNames.test.js
  test/store/reducers/tokenNetwork.test.js
  test/utils/web3.test.js
Labels: enhancement, unlock light

#99 RLP-820 Pass internal_msg_identifier in register secret
  src/store/actions/secret.js
  src/utils/messageManager.js
Labels: enhancement, register secret light

#100 RLP-821 send internal_msg_identifier in unlock request
  src/store/actions/unlock.js
  src/utils/messageManager.js
Labels: enhancement, unlock light

#101 RLP-774: generalize LC onboarding
  src/store/actions/onboarding.js
  src/store/epics/services.js
Labels: transport
